# Generated by Django 4.2 on 2024-12-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0002_alter_networklink_supplier_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networklink",
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
    ]
