# Generated by Django 4.2 on 2024-12-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0006_alter_product_network_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="network_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="chain.networklink",
                verbose_name="Звено сети",
            ),
        ),
    ]
