# Generated by Django 4.2 on 2025-01-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0008_remove_product_network_link_product_network_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=255, verbose_name="Улица")),
                (
                    "house_number",
                    models.CharField(max_length=10, verbose_name="Номер дома"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="networklink",
            name="city",
        ),
        migrations.RemoveField(
            model_name="networklink",
            name="country",
        ),
        migrations.RemoveField(
            model_name="networklink",
            name="house_number",
        ),
        migrations.RemoveField(
            model_name="networklink",
            name="street",
        ),
        migrations.AddField(
            model_name="networklink",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chain.address",
                verbose_name="Адрес",
            ),
        ),
    ]
