# Generated by Django 4.2 on 2025-01-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0009_address_remove_networklink_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
    ]
